exclude_paths:
- "versioneer.py"
- "gs_manager/_version.py"
- "config"
- "db"
- "dist"
- "features"
- "**/node_modules"
- "script"
- "**/spec"
- "**/test"
- "**/tests"
- "**/vendor"
- "**/*.d.ts"
plugins:
    pep8:
        enabled: true
engines:
    duplication:
        enabled: true
        config:
            lanuages:
                - python:
